version: '3.8'

services:
  # n8n - Plataforma de automatización
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=PSW1234
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_ENCRYPTION_KEY=unaClaveDeEncriptaciónMuySegura
      - NODE_ENV=production
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres

  # Base de datos para n8n
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=PSW1234
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Servidor LLM local (Ollama)
  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    #command: ollama run mistral:7b

  # Interfaz web para tu LLM local
  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    restart: always
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - PUBLIC_OLLAMA_API_BASE_URL=http://172.16.0.190:11434/api
    depends_on:
      - ollama

  # Servicio de la aplicación web Streamlit
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    volumes:
      - ./documentos:/app/documentos  # Montar carpeta de documentos
      - ./faiss_index:/app/faiss_index  # Montar carpeta para el índice
    ports:
      - "8501:8501"  # Puerto de Streamlit
#      - "8502:8502"  # API
#      - "8000:8000"  # Puerto de FastAPI
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped

volumes:
  n8n_data:
  postgres_data:
  ollama_data:
